name: app
type: 'php:8.1'
dependencies:
    php:
        composer/composer: ^2
runtime:
    extensions:
        - redis
variables:
    php:
        memory_limit: 3072M
relationships:
    rediscache: 'cache:redis'
    blundell: 'db:blundell'
    bridge: 'db:bridge'
    brighouse: 'db:brighouse'
    byng: 'db:byng'
    cook: 'db:cook'
    debeck: 'db:debeck'
    diefenbaker: 'db:diefenbaker'
    dixon: 'db:dixon'
    errington: 'db:errington'
    ferris: 'db:ferris'
    gardencity: 'db:gardencity'
    currie: 'db:currie'
    gilmore: 'db:gilmore'
    grauer: 'db:grauer'
    hamilton: 'db:hamilton'
    homma: 'db:homma'
    kidd: 'db:kidd'
    kingswood: 'db:kingswood'
    lee: 'db:lee'
    maplelane: 'db:maplelane'
    mckay: 'db:mckay'
    mckinney: 'db:mckinney'
    mcneely: 'db:mcneely'
    mitchell: 'db:mitchell'
    quilchena: 'db:quilchena'
    spulukwuks: 'db:spulukwuks'
    steves: 'db:steves'
    tait: 'db:tait'
    talmey: 'db:talmey'
    thompson: 'db:thompson'
    tomsett: 'db:tomsett'
    westwind: 'db:westwind'
    whiteside: 'db:whiteside'
    anderson: 'db:anderson'
    blair: 'db:blair'
    elementary: 'db:elementary'
    woodward: 'db:woodward'
    wowk: 'db:wowk'
    boyd: 'db:boyd'
    hjcambie: 'db:hjcambie'
    macneill: 'db:macneill'
    mcmath: 'db:mcmath'
    mcnair: 'db:mcnair'
    mcroberts: 'db:mcroberts'
    palmer: 'db:palmer'
    slss: 'db:slss'
    jnburnett: 'db:jnburnett'
    rhs: 'db:rhs'
    careerprograms: 'db:careerprograms'
    ce: 'db:ce'
    rvs: 'db:rvs'
    training: 'db:training'
    stationstretch: 'db:stationstretch'
disk: 95000
mounts:
    /web/files:
        source: local
        source_path: files
    /tmp:
        source: local
        source_path: tmp
    /private:
        source: local
        source_path: private
    /.drush:
        source: local
        source_path: drush
    /drush-backups:
        source: local
        source_path: drush-backups
    /.console:
        source: local
        source_path: console
build:
    flavor: composer
hooks:
    build: |
        set -e
    deploy: |
        set -e
        php ./drush/platformsh_generate_drush_yml.php
        cd web
        ../drush/drush-multisite -y cache-rebuild
        ../drush/drush-multisite -y updatedb
    post_deploy: |
        set -e
        cd web
        ../drush/drush-multisite -y config-import
        # THE CODE BELOW WILL PUT SITES IN OR OUT OF MAINTENANCE MODE 1 to enable 0 to disable
        ../drush/drush-multisite state:set system.maintenance_mode 0 --input-format=integer
        ../drush/drush-multisite cr
web:
    locations:
        /:
            root: web
            expires: 5m
            passthru: /index.php
            allow: false
            rules:
                '\.(jpe?g|png|gif|svgz?|css|js|map|ico|bmp|eot|woff2?|otf|ttf)$':
                    allow: true
                ^/robots\.txt$:
                    allow: true
                ^/sitemap\.xml$:
                    allow: true
                ^/sites/sites\.php$:
                    scripts: false
                '^/sites/[^/]+/settings.*?\.php$':
                    scripts: false
        /files:
            allow: true
            expires: 5m
            passthru: /index.php
            root: web/files
            scripts: false
            rules:
                ^/files/(css|js):
                    expires: 2w
crons:
    drupal:
        spec: '*/19 * * * *'
        cmd: 'cd web ; drush core-cron'
    drush-queue-importer-preprocess:
      spec: '*/2 * * * *'
      commands:
        start: '../drush/drush-multisite queue-run preprocess_importer_queue_worker'
    drush-queue-importer-article:
      spec: '*/3 * * * *'
      commands:
        start: '../drush/drush-multisite queue-run article_importer_queue_worker'
