db:
    type: 'mariadb:10.4'
    disk: 2048
    configuration:
        schemas:
            - master
            - anderson
        endpoints:
            master:
                default_schema: master
                privileges:
                    master: admin
            anderson:
                default_schema: anderson
                privileges:
                    anderson: admin
cache:
    type: 'redis:6.0'
