db:
    type: 'mariadb:10.4'
    disk: 2048
    configuration:
        schemas:
            - master
        endpoints:
            master:
                default_schema: master
                privileges:
                    master: admin
cache:
    type: 'redis:6.0'
