db:
    type: 'mariadb:10.4'
    disk: 2048
    configuration:
        schemas:
            - anderson
            - elementary
        endpoints:
            anderson:
                default_schema: anderson
                privileges:
                    anderson: admin
            elementary:
                default_schema: elementary
                privileges:
                    elementary: admin
cache:
    type: 'redis:6.0'
